import express from 'express';
import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
const app = express();
app.use(express.json());
let config = { nombreIA: "IA" };
if (fs.existsSync('config.json')) {
  try { config = JSON.parse(fs.readFileSync('config.json', 'utf8')); } catch(e){}
}
let openRouterKey = process.env.OPENROUTER_KEY || '';
app.get('/', (req, res) => {
  const htmlUrielFiel = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Uriel Dynamic Shell</title><script src="https://tailwindcss.com"></script><style>body { background: transparent !important; margin: 0; overflow: hidden; font-family: system-ui, sans-serif; -webkit-app-region: drag; width: 100vw; height: 100vh; display: flex; items: center; justify-content: center; } .icon-btn { -webkit-app-region: no-drag; transition: all 0.2s ease-in-out; cursor: grab; } .icon-btn:hover { transform: scale(1.1); filter: brightness(1.2); } .icon-btn:active { cursor: grabbing; }</style><script>function mutarEstado(modo) { const extendido = document.getElementById('modo-extendido'); const compacto = document.getElementById('modo-compacto'); if(modo==='cerrar'){ extendido.style.setProperty('display', 'none', 'important'); compacto.style.setProperty('display', 'flex', 'important'); }else{ extendido.style.setProperty('display', 'flex', 'important'); compacto.style.setProperty('display', 'none', 'important'); } }</script></head><body class="bg-transparent select-none w-full h-full flex items-center justify-center p-0 m-0"><div id="modo-extendido" class="w-[160px] h-[230px] bg-zinc-900/80 backdrop-blur-2xl border border-zinc-800/80 rounded-[2.5rem] p-4 flex flex-col items-center justify-between shadow-2xl text-white relative" style="display: flex;"><div class="flex flex-col items-center gap-0.5 mt-1"><div class="text-zinc-500 text-xs font-mono scale-90 tracking-widest leading-none">⠇⠃</div><span class="text-[10px] text-zinc-400 font-semibold tracking-wider font-sans uppercase mt-0.5">Braille</span></div><div class="w-full flex items-center justify-between px-1 relative"><div class="flex flex-col items-center justify-center text-center w-12"><span class="text-lg icon-btn">🖐️</span><span class="text-[8px] text-zinc-400 font-medium leading-tight mt-0.5 block">Lenguaje de señas</span></div><div onclick="mutarEstado('cerrar')" class="icon-btn text-zinc-400 text-xs font-bold px-1 hover:text-amber-500 cursor-pointer z-10 transition-colors mx-auto">&gt;</div><div class="flex flex-col items-center justify-center text-center w-12"><span class="text-xl font-bold font-serif icon-btn tracking-tighter text-zinc-200">TT</span><span class="text-[8px] text-zinc-400 font-medium leading-tight mt-0.5 block">Texto</span></div></div><div class="flex flex-col items-center mb-1"><span class="text-xl icon-btn">🎙️</span><span class="text-[10px] text-zinc-400 font-semibold tracking-wider uppercase mt-0.5">Voz</span></div></div><div id="modo-compacto" class="w-[160px] h-[230px] items-center justify-center bg-transparent" style="display: none;"><div onclick="mutarEstado('abrir')" title="IA" class="icon-btn w-20 h-20 bg-zinc-950/90 border-2 border-amber-500/40 rounded-full flex items-center justify-center shadow-2xl overflow-hidden p-2.5 backdrop-blur-md animate-pulse"><img src="/logo.png" class="w-full h-full object-contain pointer-events-none" /></div></div></body></html>`;
  res.send(htmlUrielFiel);
});
app.get('/logo.png', (req, res) => { res.sendFile(path.resolve('logo.png')); });
app.post('/api/chat', async (req, res) => { res.json({ success: true }); });
app.listen(3000, '0.0.0.0', () => {});