import path from 'path';
export function obtenerInterfaz(userAgent, config, colorFondo, efectoBlur, estiloBorder, radioBordes) {
  let iconBraille = '&#x2817;&#x2803;'; let iconSeñas = '🙌'; let iconTexto = 'Tᴛ'; let iconVoz = '🎙️';
  if (userAgent.includes('android') || userAgent.includes('watch')) {
    radioBordes = '50px'; colorFondo = 'rgba(10, 10, 10, 0.98)'; efectoBlur = ''; estiloBorder = 'none';
    iconBraille = '⠇⠃'; iconSeñas = '🫱'; iconTexto = '⌨'; iconVoz = '🎧';
  } else if (userAgent.includes('iphone') || userAgent.includes('ipad')) {
    radioBordes = '30px'; colorFondo = 'rgba(28, 28, 30, 0.9)'; efectoBlur = 'backdrop-filter: blur(20px);'; estiloBorder = 'none';
  }
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>IA PolyOS</title><script src="https://tailwindcss.com"></script><style>body { background: transparent !important; margin: 0; overflow: hidden; font-family: system-ui, sans-serif; width: 100vw; height: 100vh; display: flex; items: center; justify-content: center; } .capsula-extendida { -webkit-app-region: drag; width: 140px; height: 210px; background-color: ${colorFondo}; ${efectoBlur} border: ${estiloBorder}; border-radius: ${radioBordes}; box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.6); display: flex; flex-direction: column; items: center; justify-content: space-between; padding: 20px 12px; box-sizing: border-box; cursor: move; } .capsula-compacta { -webkit-app-region: drag; width: 140px; height: 210px; display: none; align-items: center; justify-content: center; background: transparent; cursor: move; } .icon-btn { -webkit-app-region: no-drag !important; transition: transform 0.2s ease, filter 0.2s; cursor: pointer; display: flex; items: center; justify-content: center; border: none !important; background: transparent !important; box-shadow: none !important; } .icon-btn:hover { transform: scale(1.15); filter: brightness(1.4); } .icon-btn:active { transform: scale(0.95); } .middle-row { width: 100%; display: flex; flex-direction: row; items: center; justify-content: space-between; padding: 0 4px; box-sizing: border-box; }
  /* ESTILOS TRANSLÚCIDOS Y ELIMINACIÓN DE CONTORNOS */
  .braille-ico { color: rgba(255, 255, 255, 0.7) !important; font-size: 32px; font-weight: bold; line-height: 1; height: 32px; }
  .senas-ico { font-size: 26px; width: 36px; height: 36px; filter: brightness(0) invert(1) opacity(0.7); }
  .texto-ico { font-size: 26px; font-weight: 900; font-family: serif; color: rgba(255, 255, 255, 0.7) !important; letter-spacing: -1px; width: 36px; height: 36px; }
  .flecha-ico { font-size: 14px; font-weight: 900; color: rgba(255, 255, 255, 0.4); width: 20px; height: 20px; text-align: center; }
  .flecha-ico:hover { color: #ffffff; }
  .voz-ico { font-size: 26px; color: rgba(255, 255, 255, 0.7) !important; height: 36px; filter: brightness(0) invert(1) opacity(0.7); }
  .logo-circulo { -webkit-app-region: no-drag !important; width: 85px; height: 85px; background-color: ${colorFondo}; ${efectoBlur} border: ${estiloBorder}; border-radius: 50%; display: flex; items: center; justify-content: center; box-shadow: 0 15px 20px rgba(0,0,0,0.4); overflow: hidden; padding: 10px; box-sizing: border-box; }
  .logo-img { width: 100%; height: 100%; object-fit: contain; pointer-events: none; }
  </style><script>function mutar(m){ const e=document.getElementById('modo-ext'); const c=document.getElementById('modo-com'); if(m==='cerrar'){ e.style.setProperty('display','none','important'); c.style.setProperty('display','flex','important'); }else{ e.style.setProperty('display','flex','important'); c.style.setProperty('display','none','important'); } } async function dispararFuncion(m){ try{ await fetch('/api/funcion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({modulo:m})}); }catch(e){} }</script></head><body><div id="modo-ext" class="capsula-extendida"><div onclick="dispararFuncion('braille')" title="Braille" class="braille-ico icon-btn">${iconBraille}</div><div class="middle-row"><div onclick="dispararFuncion('señas')" title="Lenguaje de Señas" class="senas-ico icon-btn">${iconSeñas}</div><div onclick="mutar('cerrar')" class="flecha-ico icon-btn">&gt;</div><div onclick="dispararFuncion('texto')" title="Texto" class="texto-ico icon-btn">${iconTexto}</div></div><div onclick="dispararFuncion('voz')" title="Voz" class="voz-ico icon-btn">${iconVoz}</div></div><div id="modo-com" class="capsula-compacta"><div onclick="mutar('abrir')" class="icon-btn logo-circulo"><img src="/logo.png" class="logo-img" /></div></div></body></html>`;
}